# SillyTavern Config for HuggingFace Spaces
dataRoot: ./data
listen: true
listenAddress:
  ipv4: 0.0.0.0
  ipv6: '[::]'
protocol:
  ipv4: true
  ipv6: false
port: 8000
whitelistMode: false
basicAuthMode: false
securityOverride: true
disableCsrfProtection: true
skipContentCheck: true
