# SillyTavern Config for Cloud Hosting
dataRoot: ./data
listen: true
listenAddress:
  ipv4: 0.0.0.0
  ipv6: '[::]'
protocol:
  ipv4: true
  ipv6: false
port: 8000
whitelistMode: false
basicAuthMode: false
securityOverride: true
disableCsrfProtection: true
skipContentCheck: true
autorun: true
avoidLocalhost: true
browserLaunch:
  enabled: false
hostWhitelist:
  enabled: false
  scan: false
  hosts:
    - .code.run
